apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: winterfell-infra
  labels:
    run: docker-registry
spec:
  selector:
    app: docker-registry
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 5000