apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: winterfell-o11y
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
            - mountPath: /etc/grafana/provisioning/dashboards
              name: dashboards-config
            - mountPath: /var/lib/grafana/dashboards
              name: dashboards-data
            - mountPath: /var/lib/grafana/dashboards/k8s-addons-prometheus
              name: k8s-addons-prometheus
            - mountPath: /var/lib/grafana/dashboards/k8s-addons-trivy-operator
              name: k8s-addons-trivy-operator
            - mountPath: /var/lib/grafana/dashboards/k8s-system-api-server
              name: k8s-system-api-server
            - mountPath: /var/lib/grafana/dashboards/k8s-system-coredns
              name: k8s-system-coredns
            - mountPath: /var/lib/grafana/dashboards/k8s-views-namespaces
              name: k8s-views-namespaces
            - mountPath: /var/lib/grafana/dashboards/k8s-views-pods
              name: k8s-views-pods
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: dashboards-config
          configMap:
            name: grafana-dashboards-config
        - name: dashboards-data
          configMap:
            name: grafana-k8s-dashboards
        - name: k8s-addons-prometheus
          configMap:
            name: dashboards-k8s-addons-prometheus
        - name: k8s-addons-trivy-operator
          configMap:
            name: dashboards-k8s-addons-trivy-operator
        - name: k8s-system-api-server
          configMap:
            name: dashboards-k8s-system-api-server
        - name: k8s-system-coredns
          configMap:
            name: dashboards-k8s-system-coredns
        - name: k8s-views-namespaces
          configMap:
            name: dashboards-k8s-views-namespaces
        - name: k8s-views-pods
          configMap:
            name: dashboards-k8s-views-pods
