apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: winterfell-o11y
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus_datasource
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true
      - name: Loki
        type: loki
        uid: loki_datasource
        access: proxy
        url: http://loki:3100
        editable: true
