apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winterfell-pvc
  namespace: winterfell-infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 4Gi
