apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: winterfell-o11y
  labels:
    app: node-exporter
spec:
  ports:
    - port: 9100
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: node-exporter
