apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: winterfell-o11y
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: http-prometheus
      protocol: TCP
      name: http-prometheus
