apiVersion: apps/v1
kind: Deployment
metadata:
  name: winterfell-ping
  namespace: winterfell-ping
  labels:
    app: winterfell-ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: winterfell-ping
  template:
    metadata:
      labels:
        app: winterfell-ping
    spec:
      containers:
        - name: winterfell-ping
          image: registry
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: '0.3'
              memory: '256Mi'
            requests:
              cpu: '0.3'
              memory: '256Mi'
