apiVersion: v1
kind: Service
metadata:
  name: winterfell-ping-service
  namespace: winterfell-ping
  labels:
    run: winterfell-ping
spec:
  selector:
    app: winterfell-ping
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30300
