apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: winterfell-o11y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          ports:
            - containerPort: 3100
              name: http-loki
          readinessProbe:
            httpGet:
              path: /ready
              port: http-loki
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /ready
              port: http-loki
            initialDelaySeconds: 45
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: loki-data
              mountPath: /loki
      volumes:
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: winterfell-o11y
spec:
  ports:
    - port: 3100
      protocol: TCP
      targetPort: http-loki
  selector:
    app: loki
