apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: winterfell-o11y
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /run/promtail/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - cri: {}
        relabel_configs:
          # Extract app name from pod labels
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - __meta_kubernetes_pod_label_app
              - __meta_kubernetes_pod_name
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: app
          # Standard labels
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
            action: replace
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
            action: replace
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
            action: replace
          - source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: node_name
            action: replace
          # Fix the path to match CRI log format
          - source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
            action: replace
            separator: /
            replacement: /var/log/pods/*$1/*.log
          # Handle pods with config hash annotations
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            regex: true/(.*)
            separator: /
            source_labels:
              - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
              - __meta_kubernetes_pod_container_name
            target_label: __path__
          # Map all the other Kubernetes labels
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
